language: ruby

script: "bundle exec rake test"

cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

notifications:
  email:
    recipients:
      - konstantin@ilchenko.by
    on_failure: change
    on_success: never